# general settings
name: train_HiRA_SR_SRx2_DF2K
model_type: SwinIRModel
scale: 2
num_gpu: auto
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: D:/1Datasets/DF2K/HR_sub
    dataroot_lq: D:/1Datasets/DF2K/LR_bicubic/X2_sub
    meta_info_file: D:/1Datasets/DF2K/meta_info_DF2Ksub_GT.txt 
    io_backend:
      type: disk
    
    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: D:/1Datasets/SR_eval_intact/HR/Set5/x2
    dataroot_lq: D:/1Datasets/SR_eval_intact/LR/LRBI/Set5/x2
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: D:/1Datasets/SR_eval_intact/HR/Set14/x2
    dataroot_lq: D:/1Datasets/SR_eval_intact/LR/LRBI/Set14/x2
    io_backend:
      type: disk

  val_3:
    name: BSD100
    type: PairedImageDataset
    dataroot_gt: D:/1Datasets/SR_eval_intact/HR/BSD100/x2
    dataroot_lq: D:/1Datasets/SR_eval_intact/LR/LRBI/BSD100/x2
    io_backend:
      type: disk

  val_4:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: D:/1Datasets/SR_eval_intact/HR/Urban100/x2
    dataroot_lq: D:/1Datasets/SR_eval_intact/LR/LRBI/Urban100/x2
    io_backend:
      type: disk

  val_5:
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: D:/1Datasets/SR_eval_intact/HR/Manga109/x2
    dataroot_lq: D:/1Datasets/SR_eval_intact/LR/LRBI/Manga109/x2
    io_backend:
      type: disk

# network structures
network_g:
  type: HiRA_SR
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 8
  img_range: 1.
  depths: [6,6,6,6]
  embed_dim: 60
  num_heads: [6,6,6,6]
  mlp_ratio: 2
  upsampler: 'pixelshuffledirect'
  resi_connection: '1conv' # '1conv'
  use_rand_shift : false
  reduction_FB: 5 # 5
  reduction_RMCB: 20 # 20

# path
path:
  pretrain_network_g: weights/002_lightweightSR_DIV2K_s64w8_SwinIR-S_x2.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [500000,800000,900000,950000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: 1000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
